/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.saquicelaj_villae_observer;


import Observador.ObservadorCarga;
import Observador.ObservadorDescarga;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.Timer;

/**
 *
 * @author Jonna; Erika Gil
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /* ----------- PRINCIPAL -------------*/
    private Timer reloj;
    private int minutos, segundos, cs;
    private ObservadorCarga obCarga;
    private ObservadorDescarga obDescarga;
    private SujetoBateria sBateria;
    private int cantidadB;
    private int tiempoRestante;

    public VentanaPrincipal() {
        initComponents();
        this.lbTextoRestante.setVisible(false);
        this.lbTiempoRestante.setVisible(false);
        
        setLocationRelativeTo(null);

        reloj = new Timer(10, acciones);
        sBateria = new SujetoBateria();
        obCarga = new ObservadorCarga(sBateria);
        obDescarga = new ObservadorDescarga(sBateria);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCargar = new javax.swing.JButton();
        btDesconectar = new javax.swing.JButton();
        btDescargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBateria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbReloj = new javax.swing.JLabel();
        lbTextoRestante = new javax.swing.JLabel();
        lbTiempoRestante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCargar.setText("Cargar");
        btCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCargarActionPerformed(evt);
            }
        });

        btDesconectar.setText("Desconectar");
        btDesconectar.setEnabled(false);
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });

        btDescargar.setText("Descargar");
        btDescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDescargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Bateria");

        txtBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBateriaActionPerformed(evt);
            }
        });

        jLabel2.setText("%");

        jLabel3.setText("Tiempo");

        lbReloj.setText("00:00");

        lbTextoRestante.setText("Tiempo restante");

        lbTiempoRestante.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lbTextoRestante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtBateria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btDesconectar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btDescargar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCargar)
                    .addComponent(jLabel1)
                    .addComponent(txtBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDesconectar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lbReloj)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTextoRestante)
                    .addComponent(lbTiempoRestante))
                .addGap(4, 4, 4)
                .addComponent(btDescargar)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ActionListener acciones = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            //Si desea apresurar el tiempo
            cs += 2;
            if (cs == 100) {
                cs = 0;
                ++segundos;
            }
            if (segundos == 60) {
                segundos = 0;
                minutos++;
                tiempoRestante -=1;

                if (sBateria.isEstadoEnCarga()) {
                    if (cantidadB < 100) {
                        if (cantidadB == 99) {
                            cantidadB += 1;
                        } else {
                            cantidadB += 2;
                        }
                        
                    }
                }else{
                    if (cantidadB > 0) {
                        if (cantidadB == 1) {
                            cantidadB -= 1;
                        } else {
                            cantidadB -= 2;
                        }
                        
                    }
                }
                sBateria.setPorcentajeBateria(cantidadB);

            }
            if (minutos == 60) {
                minutos = 0;

            }
            actualizarVentana();
        }

    };

    public void actualizarVentana() {
        String tiempo = " " + minutos + ": " + segundos;
        String timeRest = tiempoRestante + " min.";
        
        txtBateria.setText(String.valueOf(cantidadB));
        this.lbTiempoRestante.setText(timeRest);
        lbReloj.setText(tiempo);

    }


    private void btCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCargarActionPerformed
        reloj.start();
        this.btDesconectar.setEnabled(true);
        btCargar.setEnabled(false);
        btDescargar.setEnabled(true);
        
        this.txtBateria.setEnabled(false);
        
        this.lbTextoRestante.setVisible(true);
        this.lbTiempoRestante.setVisible(true);
        

        //Bateria
        sBateria.setEstadoEnCarga(true);
        cantidadB = Integer.valueOf(this.txtBateria.getText());
        sBateria.setPorcentajeBateria(cantidadB);
        
        tiempoRestante = (100 - cantidadB)/2;
        
        


    }//GEN-LAST:event_btCargarActionPerformed

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        if (reloj.isRunning()) {
            reloj.stop();
            btCargar.setEnabled(true);
        }
        btCargar.setText("Iniciar");
        btDescargar.setEnabled(false);
        btDesconectar.setEnabled(false);

        minutos = 0;
        segundos = 0;

        actualizarVentana();


    }//GEN-LAST:event_btDesconectarActionPerformed

    private void btDescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDescargarActionPerformed
        btCargar.setEnabled(true);
        this.btDesconectar.setEnabled(true);
        this.lbTextoRestante.setVisible(false);
        this.lbTiempoRestante.setVisible(false);
        

        //Bateria
        sBateria.setEstadoEnCarga(false);
        cantidadB = Integer.valueOf(this.txtBateria.getText());
        sBateria.setPorcentajeBateria(cantidadB);
        
        
        
    }//GEN-LAST:event_btDescargarActionPerformed

    private void txtBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBateriaActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCargar;
    private javax.swing.JButton btDescargar;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbReloj;
    private javax.swing.JLabel lbTextoRestante;
    private javax.swing.JLabel lbTiempoRestante;
    private javax.swing.JTextField txtBateria;
    // End of variables declaration//GEN-END:variables
}
